import { Header } from "@/Application/Components/Header/Header";
import { Footer } from "@/Application/Components/Footer/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header /> {children}
        <Footer />
      </body>
    </html>
  );
}
